# Generated by Django 4.2.6 on 2023-11-30 14:58

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_quizcategory_quiz_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='deadline',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quiz',
            name='total_questions',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(5)]),
        ),
    ]
