# Generated by Django 4.2.6 on 2023-11-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_quiz_deadline_alter_quiz_total_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='deadline',
            field=models.DateTimeField(null=True),
        ),
    ]
