# Generated by Django 4.2.6 on 2023-12-01 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_alter_quiz_deadline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='category',
            new_name='subject',
        ),
    ]
