# Generated by Django 4.2.6 on 2023-12-01 21:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_rename_category_quiz_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresponse',
            name='selected_option',
        ),
        migrations.AddField(
            model_name='userresponse',
            name='selected_options',
            field=models.ManyToManyField(related_name='user_responses', to='my_app.option'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='total_questions',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(10)]),
        ),
    ]
