# Generated by Django 4.2.6 on 2023-12-01 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_remove_userresponse_selected_option_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresponse',
            name='selected_options',
        ),
        migrations.AddField(
            model_name='userresponse',
            name='selected_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_responses', to='my_app.option'),
        ),
    ]
