# Generated by Django 4.2.6 on 2023-12-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='category',
            field=models.CharField(choices=[('Biomedical Engineering', 'Biomedical Engineering'), ('Computer Science', 'Computer Science'), ('Electrical and Computer Engineering', 'Electrical and Computer Engineering'), ('Engineering Design Division', 'Engineering Design Division'), ('Materials Science and Engineering', 'Materials Science and Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Systems Science and Industrial Engineering', 'Systems Science and Industrial Engineering')], default=('Computer Science', 'Computer Science')),
        ),
    ]
